### ISSUE TITLE
How to find untagged articles?

### ISSUE THREAD

**Issue by ddeimeke** [artur-shaik/wallabag-client#10]
I did not find a way to find untagged articles in my installation.

**Comment by artur-shaik** [comment]
Hm, seems like it's a feature request.

**Comment by ddeimeke** [comment]
Do you need any formal request from my side?

**Comment by artur-shaik** [comment]
No, will look what I can do. 

20 мая 2021 г. 18:58:18 GMT+06:00, Dirk Deimeke ***@***.***> пишет:
>Do you need any formal request from my side?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/artur-shaik/wallabag-client/issues/10#issuecomment-845094029

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by ddeimeke** [comment]
Thank you!

**Comment by ddeimeke** [comment]
Unfortunately it does not work yet. I have about 1000 untagged articles and "list --untagged" only returns one of them (the first).

If I tag the first article it returns no article (around the first 40 articles are tagged, earlier ones are not, the oldest ones are tagged as well).

**Comment by artur-shaik** [comment]
@ddeimeke you are right, could you try last release, please.

**Comment by ddeimeke** [comment]
@artur-shaik That work perfectly well.

Thanks a lot for your support.
