### ISSUE TITLE
Please add an option to tag an article

### ISSUE THREAD

**Issue by ddeimeke** [artur-shaik/wallabag-client#11]
Thanks in advance for your tremendous support.

Now, that I found all untagged articles I like to tag articles as well.

I suggest doing something like

```
wallabag update <id> --addtag tag1,tag2,tag3
wallabag update <id> --deltag tag1,tag2,tag3
```

**Comment by artur-shaik** [comment]
I think you can do it with 'tags' command. 

24 мая 2021 г. 13:10:03 GMT+06:00, Dirk Deimeke ***@***.***> пишет:
>Thanks in advance for your tremendous support.
>
>Now, that I found all untagged articles I like to tag articles as well.
>
>I suggest doing something like
>
>```
>wallabag update <id> --addtag tag1,tag2,tag3
>wallabag update <id> --deltag tag1,tag2,tag3
>```
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/artur-shaik/wallabag-client/issues/11

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by ddeimeke** [comment]
Yes, that works.

Thanks a lot.
