### ISSUE TITLE
Export to markdown

### ISSUE THREAD

**Issue by uGeek** [artur-shaik/wallabag-client#12]
It works very well to be able to export to json, but ... I could add the possibility of exporting to markdown. That would be amazing.

Thanks.
Great app

**Comment by artur-shaik** [comment]
should work in `1.8.0` with such command: `wallabag export -f markdown 207`.

**Comment by uGeek** [comment]
It's fantastic!!!

Many thanks

**Comment by artur-shaik** [comment]
@uGeek glad you like it. Give me know if you find any bugs.
