### ISSUE TITLE
Fails to run with error importing wcwidth

### ISSUE THREAD

**Issue by klundry** [artur-shaik/wallabag-client#16]
My best guess is a python upgrade broke it. Nothing with wallabag-client has been changed at all and was working normally earlier in the week. When I went to run it yesterday  get 

> from wcwidth import wcwidth
> ImportError: cannot import name 'wcwidth' from 'wcwidth' (unknown location)

**Comment by artur-shaik** [comment]
Hm, what if you try to install wcwidth?

```
pip install wcwidth
```

**Comment by klundry** [comment]
Huh, I installed wcwidth and it's working again. I'm not sure why wcwidth disappeared when it was working fine a few days ago.

**Comment by artur-shaik** [comment]
Wallabag-client doesn't use wcwidth directly. I guess it used by `tabulate`. I don't know why it could disappear, too.
