### ISSUE TITLE
List by multiple tags

### ISSUE THREAD

**Issue by eriteric** [artur-shaik/wallabag-client#17]
I would like to list articles with shared multiple tags, I thought I had done this before but I'm getting some different results now.
For each new tag I add, I get more results, not less. So it seems to be doing an OR search, not an AND search.

example command: `wallabag list -g "tag" -g "tag -g "tag"`

- python 3.10.2
- wallabag-client installed with pipx
- I noticed the `wallabag --version` command gives an error, but it is the latest 1.8.3 as listed from pipx

**Comment by artur-shaik** [comment]
Try using comma:

```
wallabag list -g tag1,tag2,tag3
```

**Comment by artur-shaik** [comment]
> I noticed the wallabag --version command gives an error, but it is the latest 1.8.3 as listed from pipx

thanks, should be fixed now

**Comment by eriteric** [comment]
> Try using comma:
> 
> ```
> wallabag list -g tag1,tag2,tag3
> ```

alright, that works. thank you
