### ISSUE TITLE
Update Package requirements - click==7.0 does not function

### ISSUE THREAD

**Issue by fruchtblase** [artur-shaik/wallabag-client#18]
Hello,

thanks for the great software! I just spent some time figuring out, why it refused to run on my machine. Turns out the culprit was  the click package. After I upgraded from 7.0 (which is the minimum required in setup.py) to 8.1.3 everything worked as expected. Hope this report helps in making the software even better!
Kind regards :)

**Comment by artur-shaik** [comment]
Hello. Glad you like it!

Thanks for info, will update requirements.
