### ISSUE TITLE
Follow HTTP redirects?

### ISSUE THREAD

**Issue by akosiaris** [artur-shaik/wallabag-client#3]
Hello,

First off, thanks for this tool. I 've started using it and I must say I find it quite useful.

However, I am meeting the following problem. Trying to submit some URLs to my wallabag instance via it I get

```
Error: An unknown error occured. 301
```

Which, unsurprisingly is an HTTP 301 status code, returned when visiting the submitted URL, with the corresponding `Location` HTTP header set in the response to the moved place of the page I want to add in wallabag. Also unsurprisingly, this might be the first in a series of 301s and/or 302s that need to be followed to end up in the wanted page. 

Any chance wallabag can support following redirects? Many thanks!

**Comment by artur-shaik** [comment]
Hello.

Does it happen on every url? If not, can you share some for me to test?

**Comment by akosiaris** [comment]
> Hello.
> 
> Does it happen on every url? If not, can you share some for me to test?

Hi. Thanks for responding so quickly.

No, it does not happen on every url, only on urls that the origin server sends a 301 or 302 for them. e.g. 

Those will **NOT** return `Error: An unknown error occured. 301`

```
wallabag add 'https://www.tensorflow.org/'
wallabag add 'https://codahale.com/you-cant-sacrifice-partition-tolerance/'
wallabag add 'https://www.nayuki.io/page/a-fundamental-introduction-to-x86-assembly-programming'
```

These **WILL** return `Error: An unknown error occured. 301`

```
wallabag add 'https://www.quantamagazine.org/20160428-entanglement-made-simple/'
wallabag add 'http://the-paper-trail.org/blog/distributed-systems-theory-for-the-distributed-systems-engineer/'
wallabag add 'http://www.ft.com/cms/s/2/1d805534-1185-11e6-839f-2922947098f0.html?siteedition=uk#axzz4JgOWxyet'
wallabag add 'https://github.com/saiprashanths/dl-setup'
```

Going through a curl -v will show why. e.g.

```
curl -v -o /dev/null http://the-paper-trail.org/blog/distributed-systems-theory-for-the-distributed-systems-engineer/

[snipping output for brevity]
< HTTP/1.1 301 Moved Permanently
< Cache-Control: public, max-age=0, must-revalidate
< Content-Length: 113
< Content-Type: text/plain
< Date: Wed, 11 Nov 2020 12:30:57 GMT
< Location: https://the-paper-trail.org/blog/distributed-systems-theory-for-the-distributed-systems-engineer/
```

Note that the redirect here is from HTTP to HTTPS, but other cases exist as well, e.g. quanta magazine seems to have altered the way their urls are constructed, while trying to not break them. So `https://www.quantamagazine.org/20160428-entanglement-made-simple/` redirects via a 301 to `http://www.quantamagazine.org/entanglement-made-simple-20160428` (note it's HTTP, not HTTPS), which redirects (again via a 301) to the HTTPS version of that url.

Following those redirects ends up in a url that is submit-able to wallabag just fine manually. Unless there is a real reason to not follow those redirects automatically, it probably makes sense to do so. Feel free to put it behind a flag like curl's -L if you want, although I 'd suggest making it the default.

One thing that is puzzling to me, is why wallabag API isn't doing that on its own. It does follow the redirects and properly parses the end url, if submitted via the web interface.

**Comment by artur-shaik** [comment]
Actually, there was a bug. Thanks for report. v1.2.1 should fix it.

**Comment by akosiaris** [comment]
> Actually, there was a bug. Thanks for report. v1.2.1 should fix it.

I can confirm. After updating I no longer have this issue. Many thanks for e4e22d9 and the quick response.
